### PR TITLE
Calcualte wpm based on final words typed

### LINKED ISSUE #17: WPM calculated based on the final words typed
Currently the WPM is estimated as the number of characters typed divided by 5 as an average word length. This makes sense when typing words from a dictionary as they tend to be longer than the average word length. Also it nulls the variation of the WPM based on the specific words selected at the start of the game.

```lua
        wpm = (n_chars - n_mistakes) / 5 * (60 / time_sec)
        accuracy = (n_chars - n_mistakes) / n_keypresses * 100
```

On the other hand, when typing sentences, a more adequate calculation would be to take into account the actual content being typed. 

It makes sense to keep both approaches and let the user choose as an option.

Also, currently correcting mistakes in typing isn't taken into account. There can be arguments for and against this but it makes sense to also take this into account.

At the end the WPM and Accuracy should be calculated like so:
```lua
        wpm = n_words * (60 / time_sec)
        accuracy = n_correct / n_words * 100
```

### PR DESCRIPTION
**Pull request by gerazov**
Closes #17

### CODE REVIEW

**Comment by gerazov** [comment]
I can't rebase this - it deletes the changes in `stats.lua`. I'm not sure what happened.

**Comment by gerazov** [comment]
Ok merged the no modification hack - this is good to go :+1:

**Comment by NStefan002** [comment]
Hi. I'm sorry for not getting back to you sooner. This has a few issues: 
- inconsistency with option name (`final_words_typed_wpm` in config.lua and `real_wpm` in some other files)
- the name for the new option is confusing, as well as its description in the README
- there are a lot of left-out print statements (I guess that was used for debugging)
- some undefined param in line 11 of stats.lua, also stylua not applied (that's my bad I'll update github actions to check for that)

Also, this is not a problem, but just to make things a little bit easier - you don't have to manually write docs (doc/speedtyper.nvim.txt) github actions will do that for you.

Thanks for this, it's a great suggestion, but I can't quite understand this code enough to maintain it myself.

**Comment by gerazov** [comment]
No worries, thanks for taking a look :+1: 

The code may need some brushing up but it does work - I've been using it for the past week  :wink:

**Pull request closed without merging**
